### PR TITLE
snapcraft: add python3-setuptools-scm

### LINKED ISSUE #77: Build fails with `ImportError: cannot import name 'version_tuple' from 'dvc.version'`
This was introduced in https://github.com/iterative/dvc/commit/6e73bd0b5bf310880a767319e212aa77c2e3c2ce

### PR DESCRIPTION
**Pull request by efiop**
Fixes #77

### CODE REVIEW

**Comment by efiop** [comment]
Oh, we actually generate this file here. Closing.
