### ISSUE TITLE
Build fails with `ImportError: cannot import name 'version_tuple' from 'dvc.version'`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc-snap#77]
This was introduced in https://github.com/iterative/dvc/commit/6e73bd0b5bf310880a767319e212aa77c2e3c2ce

**Comment by efiop** [comment]
For the record: first step https://github.com/iterative/dvc-snap/commit/4275ea4d3c2762c880fbe1ae0ceb5f31c154c37f
